In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [-3, 4]])
b = np.array([[4, 5, 6], [7, 8, 9]])
c = np.array([[-2, 3], [0, 2], [1, -1]])

In [6]:
np.dot(a, np.dot(b, c))

array([[-12,  72],
       [-14,  64]])

In [7]:
np.dot(np.dot(a, b), c)

array([[-12,  72],
       [-14,  64]])

In [1]:
def __init__(self,
    input_neurons, # 入力層のニューロン数
    hidden_neurons, # 隠れ層のニューロン数
    output_neurons, # 出力層のニューロン数
    learning_rate # 学習率
    ):
    # 入力層、隠れ層、出力層のニューロン数をインスタンス変数に代入
    self.inneurons = input_neurons # 入力層のニューロン数
    self.hneurons = hidden_neurons # 隠れ層のニューロン数
    self.oneurons = output_neurons # 出力層のニューロン数
    # 学習率をインスタンス変数に代入
    self.lr = learning_rate

In [2]:
input_neurons = 10 # 入力層のニューロンの数
hidden_neuronss = 10 # 隠れ層のニューロンの数
output_neurons = 10 # 出力層のニューロンの数
learning_rate = 0.1 # 学習率
# neuralNetworkオブジェクトの生成
n = neuralNetwork(input_neurons,
hidden_neuronss,
output_neurons,
learning_rate)

NameError: name 'neuralNetwork' is not defined

In [3]:
import numpy as np
np.random.randn(3,3)

array([[-0.47112684, -1.73271482, -0.30466371],
       [-0.69329827,  1.64566921, -0.05956412],
       [ 1.12264264, -0.86893271,  0.84747449]])

In [7]:
print(pow(4, 2))
print(pow(4, 0.5))
print(pow(4, -0.5))

16
2.0
0.5
