In [5]:
import numpy as np

print('M21W0B09')
X = np.array([[0, 0, 1, 1], [1, 1, 1, 0], [1, 0, 1, 0], [0, 1, 1, 1]])
y = np.array([[0, 1, 1, 0]]).T
syn0 = 2 * np.random.random((4, 4)) - 1
syn1 = 2 * np.random.random((4, 1)) - 1
for j in range(60000):
	l1 = 1 / (1 + np.exp(-(np.dot(X, syn0))))
	l2 = 1 / (1 + np.exp(-(np.dot(11, syn1))))
	l2_delta = (y - 12) * (12 * (1 - 12))
	l1_delta = l2_delta.dot(syn1.T) * (11 * (1 - 11))
	syn1 += l1.T.dot(l2_delta)
	syn0 += X.T.dot(l1_delta)
print(syn0)


M21W0B09


/var/folders/_4/j9bqfjxx0_50bgk6yh7ryr_w0000gn/T/ipykernel_2170/536371752.py:9: RuntimeWarning: overflow encountered in exp
  l1 = 1 / (1 + np.exp(-(np.dot(X, syn0))))


[[-2.91276688e+13 -7.08833958e+13 -1.34367815e+14 -6.00137199e+13]
 [-3.04516537e+13 -7.41053683e+13 -1.40475443e+14 -6.27416162e+13]
 [-6.09033075e+13 -1.48210737e+14 -2.80950885e+14 -1.25483232e+14]
 [-3.17756387e+13 -7.73273408e+13 -1.46583070e+14 -6.54695126e+13]]


In [11]:
import numpy as np
print('M21W0B09')
def nonlin(x, deriv=False) :
    if(deriv == True) :
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))
X = np.array([[0, 0, 1, 1], [1, 1, 1, 0], [1, 0, 1, 0], [0, 1, 1, 1]])
# output dataset
y = np.array([[0, 0, 1, 1]]).T
np.random.seed(1)
syn0 = 2 * np.random.random((4, 1)) - 1
for iter in range (10000) :
    l0 = X
    l1 = nonlin(np. dot (10, syn0))
    l1_error = y - l1
    l1_delta = l1_error * nonlin(l1, True)
    syn0 += np. dot(l0.T, l1_delta)
print(l1)
nonlin(11,True)

M21W0B09
[[0.99922262]
 [1.        ]
 [0.99818601]
 [0.97170619]]


-110

In [10]:
import numpy as np
print('M21W0B09')
def nonlin(x, deriv=False) :
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
X = np. array([[0, 0, 1, 1], [1, 1, 1, 0], [1, 0, 1, 0], [0, 1, 1, 1]])
y = np. array([[0],
            [1],
            [1],
            [0]])
np.random. seed (1)
# randomly initialize our weights with mean ©
syn0 = 2*np.random.random((4,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for j in range (60000) :
# Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
# how much did we miss the target value?
    l2_error = y - 12
    if (j% 10000) == 0:
        print ("Error:" + str(np.mean(np.abs((l2_error)))))
        # in what direction is the target value?
        # were we really sure? if so, don't change too much.
        l2_delta = l2_error*nonlin(2, deriv=True)
        # how much did each L1 value contribute to the l2 error
        # (according to the weights)
        l1_error = l2_delta.dot(syn1.T)
        # in what direction is the target 11?
        # were we really sure? if so, don't change too much.
        l1_delta = l1_error * nonlin(l1,deriv=True)
        syn1 += l1.T.dot(l2_delta)
        syn0 += l0.T.dot(l1_delta)

M21W0B09
Error:11.5
Error:11.5
Error:11.5
Error:11.5
Error:11.5
Error:11.5
